#!/bin/bash
#$ -N MIDAS_genes_snps_am_standard
#$ -e /u/home/r/rwolff/strain_stability_revisions/qsub_output
#$ -o /u/home/r/rwolff/strain_stability_revisions/qsub_output
#$ -cwd
#$ -r y
#$ -j y
#$ -l highp
#$ -l h_data=30G
#$ -l time=30:00:00
#$ -t 1-2

. /u/local/Modules/default/init/modules.sh

module load singularity

host=am

export MIDAS_DB=/u/project/ngarud/Garud_lab/midas_db_v1.2

readarray accs < /u/home/r/rwolff/strain_stability_revisions/strainstability/metagenomic_scripts/metagenomic_data_files/${host}_samples.txt

accs=( SRR9224362 SRR9224526 )
accs=(null ${accs[@]}) # zero to one start index
acc=${accs[$SGE_TASK_ID]}
echo $acc

OUTDIR=/u/scratch/r/rwolff/Poyet_midas_output/midas_files/${host}_standard/${acc}

fastq1=/u/scratch/r/rwolff/Poyet_fastq_files/${acc}_1.fastq.gz
fastq2=/u/scratch/r/rwolff/Poyet_fastq_files/${acc}_2.fastq.gz

singularity exec $H2_CONTAINER_LOC/MIDAS-1.3.2.sif run_midas.py snps $OUTDIR -1 $fastq1 -2 $fastq2 --remove_temp -d /u/project/ngarud/Garud_lab/midas_db_v1.2
singularity exec $H2_CONTAINER_LOC/MIDAS-1.3.2.sif run_midas.py genes $OUTDIR -1 $fastq1 -2 $fastq2 --remove_temp -d  /u/project/ngarud/Garud_lab/midas_db_v1.2
