#!/bin/bash
#$ -N MIDAS_genes_snps_an
#$ -e /u/home/r/rwolff/strain_stability_revisions/qsub_output
#$ -o /u/home/r/rwolff/strain_stability_revisions/qsub_output
#$ -cwd
#$ -r y
#$ -j y
#$ -l highp
#$ -l h_data=25G
#$ -l time=23:00:00
#$ -t 1-4

. /u/local/Modules/default/init/modules.sh

module load singularity

host=an

export MIDAS_DB=/u/project/ngarud/rwolff/midas_isolate_db_built/${host}

readarray accs < /u/home/r/rwolff/strain_stability_revisions/strainstability/metagenomic_scripts/metagenomic_data_files/${host}_samples.txt

accs=( SRR9224318 SRR9224322 SRR9224239 SRR9224233 )
accs=(null ${accs[@]}) # zero to one start index
acc=${accs[$SGE_TASK_ID]}
echo $acc

OUTDIR=/u/scratch/r/rwolff/Poyet_midas_output/midas_files/${host}/${acc}

fastq1=/u/scratch/r/rwolff/Poyet_fastq_files/${acc}_1.fastq.gz
fastq2=/u/scratch/r/rwolff/Poyet_fastq_files/${acc}_2.fastq.gz

singularity exec $H2_CONTAINER_LOC/MIDAS-1.3.2.sif run_midas.py genes $OUTDIR -1 $fastq1 -2 $fastq2 --remove_temp -d /u/project/ngarud/rwolff/midas_isolate_db_built/${host}
singularity exec $H2_CONTAINER_LOC/MIDAS-1.3.2.sif run_midas.py snps $OUTDIR -1 $fastq1 -2 $fastq2 --remove_temp -d /u/project/ngarud/rwolff/midas_isolate_db_built/${host}
