#!/bin/bash
#$ -N merge_MIDAS_snps_genes_am_standard
#$ -e /u/home/r/rwolff/strain_stability_revisions/qsub_output
#$ -o /u/home/r/rwolff/strain_stability_revisions/qsub_output
#$ -cwd
#$ -r y
#$ -j y
#$ -l highp
#$ -l h_data=30G
#$ -l time=23:00:00

. /u/local/Modules/default/init/modules.sh

module load singularity

host=am

export MIDAS_DB=/u/project/ngarud/Garud_lab/midas_db_v1.2

OUTDIR=/u/scratch/r/rwolff/Poyet_midas_output/merged_midas_output/${host}_standard

singularity exec $H2_CONTAINER_LOC/MIDAS-1.3.2.sif merge_midas.py snps $OUTDIR/snps -i /u/scratch/r/rwolff/Poyet_midas_output/midas_files/${host}_standard/ -t dir --sample_depth 5 --site_depth 3 --min_samples 1 --site_prev 0.0 --threads 10 > $OUTDIR/snps/species.log

singularity exec $H2_CONTAINER_LOC/MIDAS-1.3.2.sif merge_midas.py genes $OUTDIR/genes -i /u/scratch/r/rwolff/Poyet_midas_output/midas_files/${host}_standard/ -t dir --sample_depth 5 --min_samples 1 > $OUTDIR/genes/species.log








