#!/bin/bash
#$ -N merge_MIDAS_species_ae_standard
#$ -e /u/home/r/rwolff/strain_stability_revisions/qsub_output
#$ -o /u/home/r/rwolff/strain_stability_revisions/qsub_output
#$ -cwd
#$ -r y
#$ -j y
#$ -l highp
#$ -l h_data=5G
#$ -l time=23:00:00

. /u/local/Modules/default/init/modules.sh

module load singularity

host=ae

export MIDAS_DB=/u/project/ngarud/Garud_lab/midas_db_v1.2

OUTDIR=/u/scratch/r/rwolff/Poyet_midas_output/merged_midas_output/${host}_standard

mkdir -p $OUTDIR/species

singularity exec $H2_CONTAINER_LOC/MIDAS-1.3.2.sif merge_midas.py species $OUTDIR/species -i /u/scratch/r/rwolff/Poyet_midas_output/midas_files/${host}_standard -t dir > $OUTDIR/species/species.log

