#!/bin/bash                      
#$ -S /bin/bash   
#$ -N postprocess_all_steps
#$ -o /u/home/r/rwolff/strain_stability_revisions/qsub_output  
#$ -e output_error_directory       
#$ -cwd                           
#$ -r y                           
#$ -j y                            
#$ -l highp
#$ -l h_data=10G
#$ -l h_rt=23:00:00                              
#$ -t 1:9

. /u/local/Modules/default/init/modules.sh
module load python/2.7.15

source set_env_state.sh -c Korpela -d standard

hosts=( $( ./retrieve_hosts.sh ) )
export DESIRED_HOST=${hosts[$SGE_TASK_ID]}
source ./declare_config_named_atts.sh

#python core_gene_utils_orig.py

python postprocess_all_midas_data_serial.py

python create_StrainFinder_serial.py 
