#!/bin/bash                      
#$ -S /bin/bash                     
#$ -o /u/home/r/rwolff/strain_stability_revisions/qsub_output  
#$ -e output_error_directory       
#$ -cwd                           
#$ -r y                           
#$ -j y                           
#$ -l mem_free=2G    
#$ -l h_data=5G
#$ -l h_rt=8:00:00               
#$ -t 1-15               
 
. /u/local/Modules/default/init/modules.sh
module load python/2.7.15
module load gcc/4.9.5

host_arr=( am ao an )

#for host in ${host_arr[@]};
    
#    base_dir=/u/scratch/r/rwolff/Poyet_midas_output/merged_midas_output/${host}/snps

#    readarray files < ${base_dir}/species_snps.txt
#    files=(null ${files[@]}) 
#    species=${files[$SGE_TASK_ID]}

#    python postprocess_midas_data.py $species

host_arr_standard=( am ao an ae )

for host in ${host_arr_standard[@]};
    
    base_dir=/u/scratch/r/rwolff/Poyet_midas_output/merged_midas_output/${host}/snps

    readarray files < ${base_dir}/species_snps.txt
    files=(null ${files[@]}) 
    species=${files[$SGE_TASK_ID]}

    python postprocess_midas_data.py $species

done